[package]
name = "discord-ping-pong-bot"
version = "0.1.0"
authors = ["Dany Marcoux <dmarcoux@posteo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.10"
